# Generated by Django 4.2 on 2023-06-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_issue_alter_user_email_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Statement')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
            ],
        ),
    ]
