# Generated by Django 4.2 on 2023-06-27 00:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_challenge_issues_alter_challenge_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
    ]
